[package]
name = "latin-sampler"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
rand = "0.9.2"
serde = { version = "1.0", optional = true }

[dev-dependencies]
rand_chacha = "0.9.0"
serde_json = "1.0"
